import React from 'react';
import { motion } from 'framer-motion';
import { Shield, CheckCircle, AlertTriangle, Lock } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';

const SampleReportSection = () => {
  return (
    <section id="sample-report" className="py-20 bg-gray-50 dark:bg-black">
      <div className="container mx-auto px-4">
        <motion.div 
          className="text-center mb-16"
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          viewport={{ once: true }}
        >
          <h2 className="text-3xl lg:text-4xl font-extrabold text-gray-900 dark:text-white mb-4">
            What You'll Get
          </h2>
          <p className="text-xl text-gray-600 dark:text-gray-300 max-w-2xl mx-auto">
            Our comprehensive report turns confusion into clarity with actionable insights.
          </p>
        </motion.div>
        
        <motion.div 
          className="max-w-4xl mx-auto"
          initial={{ opacity: 0, scale: 0.95 }}
          whileInView={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.8 }}
          viewport={{ once: true }}
        >
          <Card className="overflow-hidden shadow-2xl dark:shadow-blue-500/10 border dark:border-gray-800">
            <CardHeader className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white">
              <CardTitle className="text-2xl flex items-center gap-3">
                <Shield className="w-6 h-6" />
                Social Media Risk Assessment Report
              </CardTitle>
              <CardDescription className="text-blue-100">
                Generated by VisaScan AI • Confidential Document
              </CardDescription>
            </CardHeader>
            <CardContent className="p-8 bg-white dark:bg-gray-900">
              <div className="grid md:grid-cols-2 gap-8">
                <div>
                  <h3 className="text-lg font-semibold mb-4">Risk Level Assessment</h3>
                  <div className="space-y-3">
                    <div className="flex items-center gap-3 p-3 rounded-lg risk-safe">
                      <CheckCircle className="w-5 h-5" />
                      <span className="font-medium">Overall Risk: SAFE</span>
                    </div>
                    <div className="flex items-center gap-3 p-3 rounded-lg risk-moderate">
                      <AlertTriangle className="w-5 h-5" />
                      <span className="font-medium">Instagram: MODERATE</span>
                    </div>
                    <div className="flex items-center gap-3 p-3 rounded-lg risk-safe">
                      <CheckCircle className="w-5 h-5" />
                      <span className="font-medium">LinkedIn: SAFE</span>
                    </div>
                  </div>
                </div>
                
                <div>
                  <h3 className="text-lg font-semibold mb-4">Flagged Content Examples</h3>
                  <div className="space-y-3">
                    <div className="p-3 bg-yellow-50 dark:bg-yellow-900/20 rounded-lg border-l-4 border-yellow-400">
                      <p className="text-sm font-medium text-yellow-800 dark:text-yellow-200">
                        Hashtag: #workandtravel
                      </p>
                      <p className="text-xs text-yellow-600 dark:text-yellow-300 mt-1">
                        May suggest unauthorized employment
                      </p>
                    </div>
                    <div className="p-3 bg-red-50 dark:bg-red-900/20 rounded-lg border-l-4 border-red-400">
                      <p className="text-sm font-medium text-red-800 dark:text-red-200">
                        Caption: "Planning to stay in the US"
                      </p>
                      <p className="text-xs text-red-600 dark:text-red-300 mt-1">
                        Could indicate immigration intent
                      </p>
                    </div>
                  </div>
                </div>
              </div>
              
              <div className="mt-8 pt-6 border-t border-border">
                <h3 className="text-lg font-semibold mb-4">Key Recommendations</h3>
                <div className="grid md:grid-cols-2 gap-4">
                  <div className="flex items-start gap-3">
                    <CheckCircle className="w-5 h-5 text-green-600 mt-0.5" />
                    <span className="text-sm">Remove or edit 3 Instagram posts mentioning work</span>
                  </div>
                  <div className="flex items-start gap-3">
                    <CheckCircle className="w-5 h-5 text-green-600 mt-0.5" />
                    <span className="text-sm">Update bio to focus on academic goals</span>
                  </div>
                  <div className="flex items-start gap-3">
                    <CheckCircle className="w-5 h-5 text-green-600 mt-0.5" />
                    <span className="text-sm">Review tagged photos for compliance</span>
                  </div>
                  <div className="flex items-start gap-3">
                    <CheckCircle className="w-5 h-5 text-green-600 mt-0.5" />
                    <span className="text-sm">Prepare explanations for flagged content</span>
                  </div>
                </div>
              </div>
              
              <div className="mt-6 p-4 bg-blue-50 dark:bg-blue-900/30 rounded-lg">
                <p className="text-sm text-blue-800 dark:text-blue-200 text-center">
                  <Lock className="w-4 h-4 inline mr-2" />
                  Unlock full 12-page detailed report for $14.99
                </p>
              </div>
            </CardContent>
          </Card>
        </motion.div>
      </div>
    </section>
  );
};

export default SampleReportSection;